name: CI

on:
    push:
        branches: ['3.x']
    pull_request: ~

jobs:
    tests:
        name: 'PHP ${{ matrix.php-version }}'
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: ['8.2', '8.3', '8.4']

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '${{ matrix.php-version }}'
                  extensions: imagick, gd
                  coverage: none

            - name: Install dependencies
              run: composer update --prefer-dist --no-progress --no-interaction

            - name: PHPUnit
              run: vendor/bin/phpunit

            - name: PHPStan
              run: vendor/bin/phpstan analyse --no-progress
